### ISSUE TITLE
Create a new fullscreen map

### ISSUE THREAD

**Issue by jwasilgeo** [jwasilgeo/ionic-esri-map#13]
Should this be a new route in the current that will just remove and eschew the current headers/footers?

Or, should this be a new app altogether?  In that case, should this repo be given additional hierarchy to house more than one ionic app?

**Comment by andygup** [comment]
> > Or, should this be a new app altogether? 

I was wondering about that as well. I was leaning towards a new app. The nice thing about a new app is it will help to show multiple approaches. And it's a great test case for anyone that wants to deviate from the template.

> > In that case, should this repo be given additional hierarchy to house more than one ionic app?

Yep, that would be my suggestion.

**Comment by jwasilgeo** [comment]
@andygup I'll go ahead and close.  Thanks for doing the reorganization to have multiple apps.

**Comment by andygup** [comment]
Thanks! I was just thinking I missed referencing these as closed in my commit.
