### ISSUE TITLE
SSL required?

### ISSUE THREAD

**Issue by andygup** [jwasilgeo/ionic-esri-map#15]
The app is working but I'm seeing the following errors being reported by Android
`"Error: SSL Required", source: http://js.arcgis.com/3.16/init.js (182)`

**Comment by jwasilgeo** [comment]
Odd. Same behavior if https is used instead for JS and CSS?

**Comment by andygup** [comment]
I'm not sure what the deal was, I haven't been able to reproduce since. It's documented just in case it shows up again.

**Comment by andygup** [comment]
I'll close this issue, we can always reopen if the issue resurfaces.
