### ISSUE TITLE
CSS conflict

### ISSUE THREAD

**Issue by jamesleeht** [jwasilgeo/ionic-esri-map#17]
Hi, regarding ionic + angular-esri-map, I followed the way it was documented here for the feature layer:
https://esri.github.io/angular-esri-map/#/examples/feature-layer

Vector tile works in ionic using the same method documented in the vector tile example, but when using feature layer, the map renders but the map is distorted.

Here is how the vector looks in ionic: http://i.imgur.com/LhOoaCp.png

Here is how the feature looks (Broken) : http://i.imgur.com/NngcUP7.png

Note that this is without the Esri ArcGis 4.0 CSS.

If i do add the esri arcgis 4.0 css:   <link rel="stylesheet" href="https://js.arcgis.com/4.0/esri/css/main.css">

It causes the map to disappear on both feature and vector. This makes me think that perhaps there is some css conflict between the ionic framework css and the ArcGIS css.

**Comment by jwasilgeo** [comment]
@jameshtlee can you provide more info on how your css and script tag resources are referenced in your index.html?  I am curious exactly which versions of the following you are referencing:
- [angular-esri-map](https://github.com/Esri/angular-esri-map#dependencies)
- ESRI ArcGIS API for JavaScript
  - JS (3.16, 4.0?)
  - CSS (3.16, 4.0?)

**Comment by jamesleeht** [comment]
4.0 for both, as well as the latest version of ionic. I managed to fix it by overriding some heights in my own CSS though for the container and fixed it already :) Thank you

**Comment by jwasilgeo** [comment]
Glad to hear you fixed it!  At JSAPI 4.0 it is probably best to specify specific heights for the map view or scene view.  Did you do something like this?

``` css
.esri-view {
  height: 500px;
}
```

**Comment by jamesleeht** [comment]
Yup, that's basically what I did. I also used !important to force it to override any of the API/framework CSS. Important to note that it has to be applied on the container within the map view or scene view directive though not the directive itself.
