### ISSUE TITLE
Double tap on map not working?

### ISSUE THREAD

**Issue by andygup** [jwasilgeo/ionic-esri-map#2]
I noticed double tapping on the map doesn't result in a zoom event.

**Comment by jwasilgeo** [comment]
Interesting catch.  I've noticed similar behavior for **angular-esri-map** with JSAPI 4 `MapView`s for that repo's example site in a mobile _browser_.  Compare a 2x-tap for the following on a mobile browser:
- https://developers.arcgis.com/javascript/beta/sample-code/layers-featurelayer/index.html
- http://esri.github.io/angular-esri-map/#/examples/feature-layer

And then, for JSAPI 3, there should be no 2x-tap issue here in a mobile browser:
https://developers.arcgis.com/javascript/beta/sample-code/layers-featurelayer/index.html

We [found](https://github.com/Esri/angular-esri-map/issues/211) that current JSAPI 4 beta3 examples are in iframes, and it is a known issue that `MapView`s and `SceneView`s aren't fully aware of their relative position if they aren't taking up the entire body height.

With all that said, it may be better for now to switch **ionic-esri-map** to use "v1" of **angular-esri-map** to work all this out with JSAPI 3, and then continue to investigate #2 and other issues (especially #6).

Thoughts?  I can make the switch if that would help with our investigation.

**Comment by andygup** [comment]
Whoops, I seem to remember that JSAPI4 does have issues with mobile, now that we're discussing it. Yep, we'd need to migrate back to v3.

**Comment by jwasilgeo** [comment]
I'll make the changes.

**Comment by jwasilgeo** [comment]
@andygup the changes are now on master via PR #11

**Comment by andygup** [comment]
Great thx. I'll pull and re-check.

**Comment by andygup** [comment]
Double tap works as expected using JS API v3

**Comment by andygup** [comment]
Closing this for now. It works in JS API v3. There will be significant improvements to the gesture manager at JS API v4.1
