### ISSUE TITLE
Pinch zoom origin possibly misaligned

### ISSUE THREAD

**Issue by andygup** [jwasilgeo/ionic-esri-map#6]
When using pinch gesture to zoom in/out the origin of the zoom doesn't seem to match the center of the touch points.

**Comment by andygup** [comment]
Closed per migrating back to JS API v3. It now works @ https://github.com/jwasilgeo/ionic-esri-map/commit/692b30a7813bd9f1af6ce39063793ee05527f8cd

**Comment by jwasilgeo** [comment]
Would it also work in the case of a very tall (or short) map, but on a view that has a lot of vertically scrollable content?

**Comment by andygup** [comment]
I'm not 100% sure. I tested it in portrait and landscape on my Nexus 5...of course that's not every exhaustive. 

It might be good to build a test app that loads a map without any headers or footers...like a basic hello world demo. I guess the $20 question is can we build single page map app with no headers and make it work within the angular life-cycle without having to manually bootstrap things?

In general, we haven't seen any issues with JS API v3 and Cordova across a wide variety of device deployments. And since, as far as I know, Ionic is using Cordova and the native WebView, I'd expect that we'd experience the similar behavior.

**Comment by jwasilgeo** [comment]
Agreed, would be ideal to have a hello world full screen map to check that out.

**Comment by andygup** [comment]
Gotcha. Then I propose we can close this issue out since it was fixed by JSAPI v3 and open a new issue to create a full screen map. Sound okay? This helps me keep things straight since I'm working on 3 projects at the same time.

**Comment by jwasilgeo** [comment]
Aboslutely--great idea.  Thanks!  See #13
